config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/search.json',to:"search#search"
  get "/search",to:"paints#search"
  get '/carts', to: 'cart#show'
  post '/cart_update', to: "cart#update_status"
  resources :paints
  root 'static_page#index'

  get "/login",to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to:"sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  post 'bot_actions/process_user_input'
  get "/introducion", to: "static_page#introducion"
  get "/news", to: "static_page#news"
  get "/open_agent", to: "static_page#open_agent"
  get "/paints", to: "paints#index"
  get "/products", to: "paints#admin_product"
  get "/create_product", to: "paints#new"
  get "/action_bot", to:"bot_actions#index"
  post "/order_items",to:"order_items#create"
  get "/manager_carts",to:"cart#admin_cart"
  post '/manager_carts', to: 'cart#update'
  post '/payments', to: 'payments#create'

  resources :users
  resources :order_items
  resources :messages, only: [:new]
  resources :payments
  resources :comments
end

app/models/paint.rb
class Paint < ApplicationRecord
    has_attached_file :paint_img,
                    styles: {paint_index: "250x350>", paint_show: "325x475>"},
                    default_url: "/images/:style/missing.png"
    
    scope :lastest, ->{order created_at: :DESC}
    scope :search, ->(q){where "name LIKE '%#{q}%'"}
    scope :order_by_name, ->{order name: :asc}
    has_many :order_items
    has_many :comments
    def lastest; end
    def self.search_by(search_term)
        where("LOWER(name) LIKE :search_term",
        search_term:"%#{search_term}%")
    end
end

app/controllers/paints_controller.rb
class PaintsController < ApplicationController
  before_action :set_paint, only: [:show,:edit, :update, :destroy]
  before_action :admin_product
  before_action :set_user

  def index
    @pagy, @paints = pagy(Paint.lastest,items: 8)
    @order_item = current_order.order_items.new
  end

  def show
    @order_item = current_order.order_items.new
    if Comment.where(:paint_id => @paint.id).nil?
      @comment=Comment.new
    else
    @comments= Comment.where(:paint_id => @paint.id)
      if current_user.nil?
      else
      @comment=Comment.new(user_id: current_user.id, paint_id:@paint.id)
      end
    end
  end
  
  def search
    @paints= Paint.where("name LIKE?","%"+params[:q]+"%")
    @order_item = current_order.order_items.new
  end

  def new
    if paint_params.empty?
      @paint = Paint.new(paint_params)
    else
    @paint = Paint.new(paint_params)
    @paint.save
    end
  end


  def edit
  end

  def create
    @paint = Paint.new(paint_params)

    respond_to do |format|
      if @paint.save
        format.html { redirect_to @paint, notice: 'Paint was successfully created.' }
        format.json { render :show, status: :created, location: @paint }
      else
        format.html { render :new }
        format.json { render json: @paint.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @paint.update(paint_params)
        format.html { redirect_to @paint, notice: 'Paint was successfully updated.' }
        format.json { render :show, status: :ok, location: @paint }
      else
        format.html { render :edit }
        format.json { render json: @paint.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @paint.destroy
    respond_to do |format|
      format.html { redirect_to paints_url, notice: 'Paint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paint
      @paint = Paint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paint_params
      params.permit(:name, :price, :description, :type_paint)
    end 

    def admin_product
      @pagy, @paints = pagy(Paint.lastest,items: 5)
    end
    def admin_cart
      @pagy, @paints = pagy(Paint.lastest,items: 5)
    end
    def set_user
      @user = current_user
    end
end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/views/paints/_form.html.erb
<%= form_with(model: paint, local: true) do |form| %>
  <% if paint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paint.errors.count, "error") %> prohibited this paint from being saved:</h2>

      <ul>
        <% paint.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :type_paint %>
    <%= form.text_field :type_paint %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paints/_paint.html.erb
 <div class="col-lg-4 col-md-6 col-sm-6">
 <div class="product__item">
    <div class="product__item__pic set-bg" >
    <a href="paints/<%= paint.id%>">
    <img src="../assets/paint/<%= paint.color%>" class="product__item__pic set-bg" >    
    </a>
        <ul class="product__item__pic__hover">

            <li><a href="#"><i class="fa fa-heart"></i></a></li>
            <li><a href="#"><i class="fa fa-retweet"></i></a></li>
            <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6><a href="#"><%= paint.name %></a></h6>
        <h5><%= paint.price %></h5>
    </div>
    <% if logged_in?%>
     <%= form_for (@order_item) do |f| %>
            <%= f.hidden_field :paint_id, value: paint.id %>
            <%= f.number_field :quantity, value: 1, min: 1%>
            <%= f.submit "Add To Cart" %>
        <% end %>
    <% else %>
    <%end%>
</div>
</div>

app/views/paints/_product.html.erb
 <tr>
    <td><%= link_to paints.id%></td>
    <td><%= link_to paints.name%></td>
    <td><%= link_to paints.price%></td>
    <td><%= link_to paints.type_paint%></td>
    <td><%= link_to paints.created_at%></td>
    <td><%= link_to paints.updated_at%></td>
    <td>
        <%= link_to 'Edit', edit_paint_path(paints) %> 
       <%= link_to "delete", paints, method: :delete, data: { confirm: "You sure?" } %>
    </td>
</tr>

app/views/paints/admin_product.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2>Customer <b>product</b></h2></div>
                    <div class="col-sm-4">
                        <a href="/create_product" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New Product</span></a>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name of Paint <i class="fa fa-sort"></i></th>
                        <th>price </th>
                        <th>Type paint<i class="fa fa-sort"></i></th>
                        <th>Created At</th>
                        <th>Update At</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                   <%=render partial: "product",  collection: @paints, as: "paints"%> 
                </tbody>
            </table>
            <div class="clearfix">
                <div class="hint-text">Showing <b>5</b> out of <b><%= Paint.count %></b> entries</div>
                 <div class="pagination" style="float: right; margin-right: 150px"><%== pagy_bootstrap_nav(@pagy)%></div>
            </div>
        </div>
    </div>  
</div>
<section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">

                        <h4>Phone</h4>
                        <p>+01-3-8888-6868</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <h4>Address</h4>
                        <p>60-49 Road 11378 New York</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <h4>Open time</h4>
                        <p>10:00 am to 23:00 pm</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <h4>Email</h4>
                        <p>hello@colorlib.com</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

app/views/paints/edit.html.erb
<h1>Editing Paint</h1>

<%= render 'form', paint: @paint %>

<%= link_to 'Show', @paint %> |
<%= link_to 'Back', paints_path %>

app/views/paints/index.html.erb
 <!-- Hero Section Begin -->
       <section class="hero hero-normal">
        <div class="container">
                <div class="col-lg-3">
                   <dropdown>
                    <input id="toggle2" type="checkbox">
                    <label for="toggle2" class="animate">KOMODO<i class="fa fa-list float-right"></i></label>
                    <ul class="animate">
                        <li><%= link_to "Introducion", introducion_path %> </li>
                        <li><%= link_to "News", news_path %> </li>
                        <li><%= link_to "Products", paints_path %> </li>
                        <li><%= link_to "Open Agent", open_agent_path %> </li>
                        <li><a href="#">Color Inspiration</a></li>
                    </ul>
                    </dropdown>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="/search">
                                <div class="hero__search__categories">
                                    All Paints
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <div class = "ui-widget">
                                <input id = "automplete-1" name ="q" type="text" placeholder="search. . . " >
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>0964703613</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div> 
                    <%= link_to image_tag("banner/wall1.png")%> 
             </div>
        
        </div>
    </section>
        <!-- Hero Section End -->

        <!-- Product Section Begin -->
        <section class="product spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-5">
                        <div class="sidebar">
                            <div class="sidebar__item">
                                <h4>Department</h4>
                                <ul>
                                    <li><a href="#">exterior_paints</a></li>
                                    <li><a href="#">interior_paints</a></li>
                            </div>
                            <div class="sidebar__item">
                                <h4>Popular Size</h4>
                                <div class="sidebar__item__size">
                                    <label for="large">
                                        Large
                                        <input type="radio" id="large">
                                    </label>
                                </div>
                                <div class="sidebar__item__size">
                                    <label for="medium">
                                        Medium
                                        <input type="radio" id="medium">
                                    </label>
                                </div>
                                <div class="sidebar__item__size">
                                    <label for="small">
                                        Small
                                        <input type="radio" id="small">
                                    </label>
                                </div>
                                <div class="sidebar__item__size">
                                    <label for="tiny">
                                        Tiny
                                        <input type="radio" id="tiny">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-7">
                        <div class="product__discount">
                        <div class="filter__item">
                            <div class="row">
                                <div class="col-lg-4 col-md-5">
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <div class="filter__found">
                                        <h6><span><%= @paints.count %></span> Products found</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                         <div class="row">
                           <%=render @paints%>
                           <div class="pagination" style="float: right; margin-right: 150px"><%== pagy_bootstrap_nav(@pagy) %></div>
                        </div> 
                    </div>
                </div>
            </div>
        </section>

app/views/paints/new.html.erb
<div class="container-xl">
<div class="row">
    <div class="col-lg-12">
          <div class="form">
            <form class="form-validate form-horizontal " id="register_form" method="get" action="">
              <div class="form-group ">
              <%= form_for(@paint) do |f| %>
                <label for="name" class="control-label col-lg-2">Full name <span class="required">*</span></label>
                <div class="col-lg-10">
                  <input class=" form-control" id="name" name="name" type="text" style="width: 500px;"/>
                </div>
              </div>
              <div class="form-group ">
                <label for="price" class="control-label col-lg-2">price <span class="required">*</span></label>
                <div class="col-lg-10">
                  <input class=" form-control" id="price" name="price" type="text" style="width: 500px;" />
                </div>
              </div>
              <div class="form-group ">
                <label for="description" class="control-label col-lg-2">Description<span class="required">*</span></label>
                <div class="col-lg-10">
                  <input class=" form-control" id="description" name="description" type="text" style="width: 500px; height:100px; " maxlength="300"  />
                </div>
              </div>
               <div class="form-group">
                  <label class="control-label col-lg-2" >Type paint</label>
                   <div class="radios">
                        <label class="label_radio" for="radio-01">
                            <input name="type_paint" id="radio-01" value="foreign paint" type="radio" checked />foreign paint
                        </label>
                        <label class="label_radio" for="radio-02">
                            <input name="type_paint" id="radio-02" value="internal paint" type="radio" /> internal paint
                        </label>
                      </div>
                </div>
              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  <button class="btn btn-primary" type="submit">Save</button>
                  <button class="btn btn-default" type="button">Cancel</button>
                </div>
              </div>
              <% end %>
            </form>
          </div>
    </div> 
  </div>
</div>

app/views/paints/search.html.erb
 <!-- Hero Section Begin -->
       <section class="hero hero-normal">
        <div class="container">
                <div class="col-lg-3">
                   <dropdown>
                    <input id="toggle2" type="checkbox">
                    <label for="toggle2" class="animate">KOMODO<i class="fa fa-list float-right"></i></label>
                    <ul class="animate">
                        <li><%= link_to "Introducion", introducion_path %> </li>
                        <li><%= link_to "News", news_path %> </li>
                        <li><%= link_to "Products", paints_path %> </li>
                        <li><%= link_to "Open Agent", open_agent_path %> </li>
                        <li><a href="#">Color Inspiration</a></li>
                    </ul>
                    </dropdown>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="/search">
                                <div class="hero__search__categories">
                                    All Categories
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <div class = "ui-widget">
                                <input id = "automplete-1" name ="q" type="text" placeholder="search. . . " >
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>

                        </div>
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>0964703613</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div> 
                    <%= link_to image_tag("banner/wall1.png")%> 
             </div>
        
        </div>
    </section>
        <!-- Hero Section End -->

        <!-- Product Section Begin -->
        <section class="product spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-5">
                        <div class="sidebar">
                            <div class="sidebar__item">
                                <h4>Department</h4>
                                <ul>
                                    <li><a href="#">exterior_paints</a></li>
                                    <li><a href="#">interior_paints</a></li>
                            </div>
                            <div class="sidebar__item">
                                <h4>Popular Size</h4>
                                <div class="sidebar__item__size">
                                    <label for="large">
                                        Large
                                        <input type="radio" id="large">
                                    </label>
                                </div>
                                <div class="sidebar__item__size">
                                    <label for="medium">
                                        Medium
                                        <input type="radio" id="medium">
                                    </label>
                                </div>
                                <div class="sidebar__item__size">
                                    <label for="small">
                                        Small
                                        <input type="radio" id="small">
                                    </label>
                                </div>
                                <div class="sidebar__item__size">
                                    <label for="tiny">
                                        Tiny
                                        <input type="radio" id="tiny">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-7">
                        <div class="product__discount">
                        <div class="filter__item">
                            <div class="row">
                                <div class="col-lg-4 col-md-5">
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <div class="filter__found">
                                        <h6><span><%= @paints.count %></span> Products found</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                         <div class="row">
                           <%=render @paints%>
                        </div> 
                    </div>
                </div>
            </div>
        </section>