config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/search.json',to:"search#search"
  get "/search",to:"paints#search"
  get '/carts', to: 'cart#show'
  post '/cart_update', to: "cart#update_status"
  resources :paints
  root 'static_page#index'

  get "/login",to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to:"sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  post 'bot_actions/process_user_input'
  get "/introducion", to: "static_page#introducion"
  get "/news", to: "static_page#news"
  get "/open_agent", to: "static_page#open_agent"
  get "/paints", to: "paints#index"
  get "/products", to: "paints#admin_product"
  get "/create_product", to: "paints#new"
  get "/action_bot", to:"bot_actions#index"
  post "/order_items",to:"order_items#create"
  get "/manager_carts",to:"cart#admin_cart"
  post '/manager_carts', to: 'cart#update'
  post '/payments', to: 'payments#create'

  resources :users
  resources :order_items
  resources :messages, only: [:new]
  resources :payments
  resources :comments
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  has_one :order
  has_many :comments
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  scope :lastest, ->{order created_at: :DESC}
  def create_cart
    carts.create(verify: 3) if save
  end

  def self.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated? attribute, remember_token
    digest = send("#{attribute}_digest")
    return false unless remember_digest

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def lastest; end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :new, :create ]
  before_action :logged_in_user, except: [:new, :show, :create ]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @pagy, @users = pagy(User.lastest,items: 5)
  end

  def new
    @user= User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
    render "new"
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
    render "edit"
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "User deleted"
      redirect_to users_path
    else
      flash[:error] = " delete fails"
      redirect_to users_url
    end
  end

  private

  def user_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    redirect_to (root_url)  unless current_user? @user
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:warming] = "user not found"
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for user, size: 80
        gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end
end

app/views/users/_user.html.erb
 <tr>
    <td><%= link_to user.id, user %></td>
    <td><%= gravatar_for user, size: 50 %>
        <%= link_to user.name, user %>
    </td>
    <td><%= link_to user.created_at, user %></td>                        
    <td><span class="status text-success">&bull;</span> Active</td>
    
    <td>
        <a href="#" class="settings" title="Settings" data-toggle="tooltip"><i class="material-icons">&#xE8B8;</i></a>
        <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
    </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="gravatar_edit">
  <%= gravatar_for @user %>
  <a href="https://gravatar.com/emails">change</a>
  </div>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
    <%= f.label :phone %>
    <%= f.text_field :phone, class: 'form-control' %>
    <%= f.label :birthday %>
    <%= f.date_field :birthday, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  
</div>
</div>

app/views/users/index.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2>User <b>Management</b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="#" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New User</span></a>						
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>						
                        <th>Date Created</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                <%=render @users%>                         
                </tbody>
            </table>
            <div class="clearfix">
                <div class="hint-text">Showing <b>5</b> out of <b><%= User.count %></b> entries</div>
                <div class="pagination" style="float: right; margin-right: 150px"><%== pagy_bootstrap_nav(@pagy)%></div>
            </div>
        </div>
    </div>
</div>     

app/views/users/new.html.erb
<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab"><%= link_to "Sing In", login_path %></label>
		<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"><%= link_to "Sing Up", signup_path %></label>
		<div class="login-form">
			<div class="sign-in-htm">
				<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<div class="group">
							<%= f.label :name %>
							<%= f.text_field :name, class: 'input' %>
						</div>
						<div class="group">
							<%= f.label :email %>
							<%= f.email_field :email, class: 'input' %>
						</div>
						<div class="group">
							<%= f.label :password %>
							<%= f.password_field :password, class: 'input' %>
						</div>
						<div class="group">
							<%= f.label :password_confirmation %>
							<%= f.password_field :password_confirmation, class: 'input' %>
						</div>
						<div class="group">
							<%= f.submit "Create my account", class: "button" %>
							</div>
					<div class="hr"></div>
					<div class="foot-lnk">
						<a href="#forgot">login</a>
					</div>
      			  <% end %>
      </div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
 <section class="hero">
<body>
    <div class="container main-secction">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 image-section">
                <img src="../assets/backgroud.jpg">
            </div>
            <div class="row user-left-part">
                <div class="col-md-3 col-sm-3 col-xs-12 user-profil-part pull-left">
                    <div class="row ">
                        <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
                            <%= gravatar_for @user %>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12 user-detail-section1 text-center">
                            <button class="btn btn-success btn-block follow">Contact</button> 
                            <button class="btn btn-warning btn-block"><%= link_to "Settings", edit_user_path(current_user) %></button>                               
                        </div>

                       
                    </div>
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12 pull-right profile-right-section">
                    <div class="row profile-right-section-row">
                        <div class="col-md-12 profile-header">
                            <div class="row">
                                <div class="col-md-8 col-sm-6 col-xs-6 profile-header-section1 pull-left">
                                    <h1><%=@user.name%></h1>
                                    <h5>user</h5>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-8">
                                        <ul class="nav nav-tabs" role="tablist">
                                                <li class="nav-item">
                                                  <a class="nav-link active" href="#profile" role="tab" data-toggle="tab"><i class="fas fa-user-circle"></i> Profile user</a>
                                                </li>
                                                <li class="nav-item">
                                                  <a class="nav-link" href="#buzz" role="tab" data-toggle="tab"><i class="fas fa-info-circle"></i> Information</a>
                                                </li>                                                
                                              </ul>
                                              
                                              <!-- Tab panes -->
                                              <div class="tab-content">
                                                <div role="tabpanel" class="tab-pane fade show active" id="profile">
                                                        <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>ID</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p><%=@user.id%></p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Name</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p><%=@user.name%></p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Email</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p><%=@user.email%></p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>telephone</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>12345678</p>
                                                                </div>
                                                            </div>
                                                           
                                                </div>
                                                <div role="tabpanel" class="tab-pane fade" id="buzz">
                                                        <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Experience</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>Expert</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Hourly Rate</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>10$/hr</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Total Projects</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>230</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>English Level</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>Expert</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Availability</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>6 months</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-12">
                                                                    <label>Your Bio</label>
                                                                    <br/>
                                                                    <p>Your detail description</p>
                                                                </div>
                                                            </div>
                                                </div>
                                                
                                              </div>
                          
                                </div>
                                <div class="col-md-4 img-main-rightPart">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="row image-right-part">
                                                <div class="col-md-6 pull-left image-right-detail">
                                                    <h6>PUBLICIDAD</h6>
                                                </div>
                                            </div>
                                        </div>
                                        <a href="http://camaradecomerciozn.com/">
                                            <div class="col-md-12 image-right">
                                                <img src="../assets/paint/1.png">
                                            </div>
                                        </a>
                                        <div class="col-md-12 image-right-detail-section2">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</section>