config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/search.json',to:"search#search"
  get "/search",to:"paints#search"
  get '/carts', to: 'cart#show'
  post '/cart_update', to: "cart#update_status"
  resources :paints
  root 'static_page#index'

  get "/login",to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to:"sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  post 'bot_actions/process_user_input'
  get "/introducion", to: "static_page#introducion"
  get "/news", to: "static_page#news"
  get "/open_agent", to: "static_page#open_agent"
  get "/paints", to: "paints#index"
  get "/products", to: "paints#admin_product"
  get "/create_product", to: "paints#new"
  get "/action_bot", to:"bot_actions#index"
  post "/order_items",to:"order_items#create"
  get "/manager_carts",to:"cart#admin_cart"
  post '/manager_carts', to: 'cart#update'
  post '/payments', to: 'payments#create'

  resources :users
  resources :order_items
  resources :messages, only: [:new]
  resources :payments
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :paint
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal
    belongs_to :user
    scope :lastest, ->{order created_at: :DESC}
    def subtotal
      order_items.collect { |order_item| order_item.valid? ? order_item.price * order_item.quantity : 0 }.sum
    end

    def lastest; end
    private
  
    def set_subtotal
      self[:subtotal] = subtotal
    end 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :paint
    belongs_to :order
    before_save :set_price
    before_save :set_total
  
    def price
      # If there is a record
      if persisted?
        self[:price]
      else
        paint.price
      end
    end
  
    def total
      price * quantity
    end
  
    private
  
    def set_price
      self[:price] = price
    end
  
    def set_total
      self[:total] = total * quantity
    end
end

app/models/paint.rb
class Paint < ApplicationRecord
    has_attached_file :paint_img,
                    styles: {paint_index: "250x350>", paint_show: "325x475>"},
                    default_url: "/images/:style/missing.png"
    
    scope :lastest, ->{order created_at: :DESC}
    scope :search, ->(q){where "name LIKE '%#{q}%'"}
    scope :order_by_name, ->{order name: :asc}
    has_many :order_items
    has_many :comments
    def lastest; end
    def self.search_by(search_term)
        where("LOWER(name) LIKE :search_term",
        search_term:"%#{search_term}%")
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  has_one :order
  has_many :comments
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  scope :lastest, ->{order created_at: :DESC}
  def create_cart
    carts.create(verify: 3) if save
  end

  def self.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated? attribute, remember_token
    digest = send("#{attribute}_digest")
    return false unless remember_digest

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def lastest; end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :load_order, except: [:index, :new, :create ,:update,]
  before_action :load_user, only: :admin_cart

  def update_status
    @order=Order.find_by_user_id(current_user.id)
    @order.update_attributes(status: "1")
    @payment=Payment.new(order_id:@order.id,user_id:current_user.id)
    @payment.save
  end

  def create
  end

  def show
    @order_items = current_order.order_items
  end


  def destroy
    if @order.destroy
      flash[:success] = "order deleted"
    else
      flash[:error] = " delete fails"
    end
  end

  def admin_cart
    @orders= Order.lastest
  end

  private

  def load_order
    @order = Order.find_by_id(session[:order_id])
    return if @order
    flash[:warming] = "order not found"
  end

  def load_user
    @users = User.find_by_id (params[:user_id])
    return if @user
    flash[:warming] = "user not found"
  end

  def card_param
    params.require(:manager_carts).permit( :status, :user_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end
  
  def create
    byebug
    environment = PayPal::SandboxEnvironment.new(ATyxGFKos4swuTzF3lxNy0e4nMsBoWVJqIvVMYMzSVZvaj99-fOHT6bceySsl9VIPwAAByWEEwIuQfPw, EMOSS6rnxfisQQQ01UXtWrvBv2WWJooThRJoQ3SVYvXZG6m9kqZJAK5K6ZjLC96UxktOOXaT-Hmw6u8R)
    client = PayPal::PayPalHttpClient.new(environment)
    request = PayPalCheckoutSdk::Orders::OrdersCaptureRequest::new(params[:order_id])
    begin
      # Call API with your client and get a response for your call
      response = client.execute(request)

      # If call returns body in response, you can get the deserialized version from the result attribute of the response
      order = response.result
      Payment.create order_id: order.id, payer_id: order.payer.payer_id
    rescue PayPalHttp::HttpError => ioe
      # Something went wrong server-side
      puts ioe.status_code
      puts ioe.headers["debug_id"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
        end
      end
    end

    def current_order
      if current_user.nil?
        Order.new
      else
        # Use Find by id to avoid potential errors
        if Order.find_by(user_id: current_user.id).nil?
          Order.create(user_id: current_user.id)
        else
          Order.find_by(user_id: current_user.id)
        end
      end
    end
end

app/helpers/bot_actions_helper.rb
module BotActionsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/introducion_helper.rb
module IntroducionHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/open_agent_helper.rb
module OpenAgentHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
	def load_order_session order
		session[:order_id] = order.id
	end

end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	 def log_in user
		session[:user_id] = user.id
	  end
	
	  def current_user
		if (user_id = session[:user_id])
		  @current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
		  user = User.find_by(id: user_id)
		  if user&.authenticated?(:remember, cookies[:remember_token])
			log_in user
			@current_user = user
			end
		end
	  end
	
	
	  def current_user? user
		user && user == current_user
	  end
	
	  def logged_in?
		current_user.present?
	  end
	
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def admin?
		session[:user_id] == 1 
	end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for user, size: 80
        gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<script src="https://www.paypal.com/sdk/js?client-id=ATyxGFKos4swuTzF3lxNy0e4nMsBoWVJqIvVMYMzSVZvaj99-fOHT6bceySsl9VIPwAAByWEEwIuQfPw"></script>

<div id="paypal-button-container"></div>

<script>
  paypal.Buttons({
    createOrder: function (data, actions) {
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '0.69'
          }
        }]
      });
    },
    onApprove: function (data, actions) {
      $.ajax({
        url: '/cart_update',
        method: 'POST',
        dataType: 'json',
        data: JSON.stringify({
          'order_id': data.orderID,
          'payer_id': data.payerID
        }),
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': $('meta[name="csrf-token"]').content
        }
      }).then(function () {
        alert("Thanh toán thành công!");
      });
}
  }).render('#paypal-button-container');
</script>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', payments_path %>